### ISSUE TITLE
Load sbot configuration flags from file

### ISSUE THREAD

**Issue by mycognosist** [cryptoscope/ssb#88]
# Allow loading of configuration flags from file

`go-sbot` configuration flags are currently set via the command line, with default values defined [in the code](https://github.com/cryptoscope/ssb/blob/master/cmd/go-sbot/main.go). I'd like to propose adding a `--config` argument which would allow for flag values to be optionally read from file.

**How it might work:**

The path for the `--config` argument defaults to `~/.ssb-go/config`:

`go-sbot --config`

An alternate path and configuration file may be specified:

`go-sbot --config /home/glyph/go-sbot-conf`

When the `--config` argument is passed, any flag values found in the file override the defaults set in code. Command line arguments override defaults and values found in file. This allows a mixture of default values, values from file and values from the command line. Hard-coded -> config file -> CLI arguments.

We could also do away with the default file idea and require that a path and filename be specified.

Example contents of the file:

```json
{
  "hops": 2,
  "ebtEnabled": true,
  "localAdv": true,
  "localDiscov": true,
  "wsPort": ":7777"
}
```

I'm happy to create a PR for this if it will be a welcome addition? I'd like this for the purposes of PeachCloud and think it might be useful for others.

@cryptix 

Are there any reasons why this is a bad idea or an undesirable addition? If not, do you have any suggested changes to the behaviour I've outlined?

**Comment by cryptix** [comment]
Right. I thought about this a bunch of times. I punted on it mostly because the number of config options was initially small. 

Only _do not want_ I have for this is using JSON. It's a particularly bad format (missing comments is a big one). Personally I'd choose TOML, maybe YAML.

I like the idea, tho because it would allow for adding stuff that feels to verbose or cumbersome with flags. Like a list of pubs to connect to, which I've only done with external scripts until now.

So, yes, definitely welcome. Ping me if you run into issues. I imagine mapping a struct to the options api will need some reflection which might be cumbersome as a starter.

**Comment by mycognosist** [comment]
Great, +1 for TOML. I'll get started on this and will pop-in with updates along the way.

**Comment by cryptix** [comment]
One more tip: Go's type system (which always initializes with zero values) makes it hard to see if a field was set in a config if you unmarshal into a struct. Let me try to examplify

```go
type exampleConfig struct {
	Hops int

	Things string
}

func main() {
	b, err := ioutil.ReadFile("path/to/config")
	check(err)

	var cfg exampleConfig
	err := toml.Unmarshal(b, &cfg)
	check(err)
	
	// cfg.Hops == 0 && cfg.Things == ""
	// no matter if hops: x was in the file or not.
	// this would be the same for json and is inherrent in go's type system
}

```

To work around this you can unmarshal into a `map[string]interface{}` and check presence of the fields with the `value, ok := m["key"]` syntax.

This is usually cumbersome to work with, because you would have to assert the types of `interface{}` before you can use them, but if you unmarshal twice you can use the map for presence and the struct for nice type checking. Best of both worlds!

**Comment by mycognosist** [comment]
Thanks for the tips! That's super helpful.

Perhaps it's best to begin by defining the layout and format of the `toml` file before I get cracking with the code.

I've basically just taken the existing flags from `initFlags()` and roughly grouped them into sections: keys, addresses, gossip / replication, directories, utilities and other. I'm using this [TOML validator](https://github.com/BurntSushi/toml/tree/master/cmd/tomlv) to ensure the config is valid.

How does this look to you?

```toml
# Supply various flags to control go-sbot options.

title = "go-sbot Configuration"

shscap = "1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=" # Secret-handshake app-key (or compatible alt-key)
hmac = "" # If set, sign with hmac hash of msg instead of plain message object using this key

lis = ":8008" # Address to listen on
wslis = ":8989" # Address to listen on for ssb-ws connections
debuglis = "localhost:6078" # Address to listen on for metrics and pprof HTTP server

hops = 1 # How many hops to fetch (1: friends, 2: friends of friends)
localadv = false # Enable sending local UDP broadcasts
localdiscov = false # Enable connecting to incoming UDP broadcasts
enable-ebt = false # Enable syncing by using epidemic-broadcast-trees (EBT)
promisc = false # Bypass graph auth and fetch remote's feed

# TODO: Need to think about how to handle the user home directory path
repo = ".ssb-go" # Where to put the log and indexes
debugdir = "" # Where to write debug output

cleanup = false # Remove blocked feeds
fsck = "" # Run a filesystem check on the repo (possible values: length, sequences)
repair = false # Run repo healing if fsck fails
reindex = false # If set, sbot exits after having it's indicies updated

nounixsock = false # Disable the UNIX socket RPC interface

version = false # Print version number and build date
```
